export const jobs = [
  {
    id: 1,
    company: "Outlier",
    title: "AI Trainer",
    location: "Remote",
    type: "Contract",
    salary: "$20–35/hr",
    category: "AI Training",
  },
  {
    id: 2,
    company: "TELUS Digital",
    title: "AI Data Annotator",
    location: "Remote",
    type: "Part-Time",
    salary: "$15–25/hr",
    category: "Data Annotation",
  },
  {
    id: 3,
    company: "Scale AI",
    title: "AI Data Trainer",
    location: "Remote",
    type: "Full-Time",
    salary: "$18–30/hr",
    category: "Machine Learning",
  },
  {
    id: 4,
    company: "Invisible Technologies",
    title: "AI Operations Specialist",
    location: "Remote",
    type: "Full-Time",
    salary: "$22–40/hr",
    category: "AI Operations",
  },
  {
    id: 5,
    company: "Sama",
    title: "Data Labeling Specialist",
    location: "Kenya",
    type: "Contract",
    salary: "$15–22/hr",
    category: "Data Annotation",
  },
];